### ISSUE TITLE
does the websocket auto reconnect if it disconnects? Or do we need to implement it ourselves?

### ISSUE THREAD

**Issue by superdude12399** [fabianboesiger/ftx#115]
does the websocket auto reconnect if it disconnects? Or do we need to implement it ourselves?

**Comment by superdude12399** [comment]
how do we know that the websocket has disconnected?

**Comment by MaxFangX** [comment]
If the websocket has disconnected, it will throw a [Tungstenite error](https://github.com/fabianboesiger/ftx/blob/main/src/ws/error.rs#L19). When that happens, the correct thing to do is to [unsubscribe from all channels](https://github.com/fabianboesiger/ftx/blob/main/src/ws/mod.rs#L127) in case the FTX exchange is still trying to talk to your websockets client, then [resubscribe](https://github.com/fabianboesiger/ftx/blob/main/src/ws/mod.rs#L93) to the channels that you need.

**Comment by MaxFangX** [comment]
Your implementing code will probably look something like this (I'm using `anyhow` `context()`s to shown what's going on)

```rust
fn infallible() -> {
    let mut ws = Ws::connect ... // initialize Ws here
    ws.subscribe(...) // subscribe to channels here
    let result = fallible(&mut ws).await;
    if let Err(e) = result {
        // handle error, unsubscribe here
        println!("There was an error: {}", e);
        ws.unsubscribe_all().await;
    }
}

fn fallible(
    ws: &mut Ws,
) -> anyhow::Result<()> {
    loop {
       let data = ws
            .next()
            .await
            .context("No data returned")?
            .context("Websockets error")?;
        println!("Websockets returned {}", data);
    }
    Ok(())
}

```

**Comment by superdude12399** [comment]
what is anyhow and context() in anyhow::Result<()> and .context("No data returned")? I don't understand those two terms and can't find it in the crate

**Comment by MaxFangX** [comment]
Anyhow is a popular crate used to propagate errors without having to define a type or enum variant for every error. It is a good crate to use in your Rust projects :) You can read about it here

https://docs.rs/anyhow/latest/anyhow/index.html

**Comment by MaxFangX** [comment]
It's been a week, so I'm closing this. Feel free to reopen a new discussion or issue if you have any more questions :)
