### ISSUE TITLE
Multiple orderbooks

### ISSUE THREAD

**Issue by SwayStar123** [fabianboesiger/ftx#117]
How would one use the websocket to listen to multiple orderbooks? Looking at the example seems like only one orderbook can be listened to at a time

Heres my code- 
```
    let solbtc = String::from("SOL/BTC");
    let solusd = String::from("SOL/USD");
    let solusdt = String::from("SOL/USDT");
    let fttbtc = String::from("FTT/BTC");
    let fttusd = String::from("FTT/USD");
    let fttusdt = String::from("FTT/USDT");
    let btcusd = String::from("BTC/USD");
    let usdtusd = String::from("USDT/USD");

    let mut solbtcorderbook = Orderbook::new(solbtc.to_owned());
    let mut solusdorderbook = Orderbook::new(solusd.to_owned());
    let mut solusdtorderbook = Orderbook::new(solusdt.to_owned());
    let mut fttbtcorderbook = Orderbook::new(fttbtc.to_owned());
    let mut fttusdorderbook = Orderbook::new(fttusd.to_owned());
    let mut fttusdtorderbook = Orderbook::new(fttusdt.to_owned());
    let mut btcusdorderbook = Orderbook::new(btcusd.to_owned());
    let mut usdtusdorderbook = Orderbook::new(usdtusd.to_owned());

    websocket.subscribe(vec![
        Channel::Orderbook(solbtc.to_owned()),
        Channel::Orderbook(solusd.to_owned()),
        Channel::Orderbook(solusdt.to_owned()),
        Channel::Orderbook(fttbtc.to_owned()),
        Channel::Orderbook(fttusd.to_owned()),
        Channel::Orderbook(fttusdt.to_owned()),
        Channel::Orderbook(btcusd.to_owned()),
        Channel::Orderbook(usdtusd.to_owned()),
    ]).await?;

    tokio::spawn(async move {
        loop {
            let data = websocket.next().await.expect("No data received").unwrap();

            match data {
                (_, Data::OrderbookData(orderbook_data)) => {

                }

                _ => panic!("Unexpected data received: {:?}", data),
            }
        }
    });

```
Now im not so sure what to put inside the match statement, as all the orderbook data is just grouped into one

In the example file -
```
(_, Data::OrderbookData(orderbook_data)) => {
                orderbook.update(&orderbook_data);
                print!("."); // To signify orderbook update
                io::stdout().flush().unwrap(); // Emits the output immediately
            }
```
the data is not categorised by symbol so im puzzled

**Comment by MaxFangX** [comment]
For my own project, I use a separate `Ws` instance for each market that I want to watch. Then, a `tokio::select!` across the `next()`s of each allows you to handle orderbook updates as soon as any of the markets you're watching emits one.

**Comment by MaxFangX** [comment]
Actually, in the code example you referenced:

```rust
(_, Data::OrderbookData(orderbook_data)) => {
                orderbook.update(&orderbook_data);
                print!("."); // To signify orderbook update
                io::stdout().flush().unwrap(); // Emits the output immediately
            } 
```

That `_` holds the market field e.g. `BTC/USD`. If you change the `_` to say, `market`, you should be able to differentiate between orderbook updates on different markets using a single `Ws` object.

**Comment by SwayStar123** [comment]
> Actually, in the code example you referenced:
> 
> ```rust
> (_, Data::OrderbookData(orderbook_data)) => {
>                 orderbook.update(&orderbook_data);
>                 print!("."); // To signify orderbook update
>                 io::stdout().flush().unwrap(); // Emits the output immediately
>             } 
> ```
> 
> That `_` holds the market field e.g. `BTC/USD`. If you change the `_` to say, `market`, you should be able to differentiate between orderbook updates on different markets using a single `Ws` object.

Oh, thats useful to know, thanks, that should fix my issue then

**Comment by fabianboesiger** [comment]
That was already a concern earlier, that's why the returned tuple includes the market field, just like @SwayStar123 suggested. I'm aware that the current implementation is not very idiomatic. Feel free to suggest improvements if you have any ideas.

**Comment by SwayStar123** [comment]
Cant really think of an improvement it works well enough for me
