### ISSUE TITLE
watch_market.rs cannot work

### ISSUE THREAD

**Issue by sunfu12** [fabianboesiger/ftx#131]
When I compile [watch_market.rs](https://github.com/fabianboesiger/ftx/blob/main/examples/watch_market.rs), there's an error:
------------------
let data = websocket.next().await.expect("No data received")?;
                                  ^^^^ method not found in `Ws`
-----------------
websocket.next() method not found. I use the latest version. How to get orderbook data in the latest sdk version?

**Comment by fabianboesiger** [comment]
It seems to work fine for me. Did you use the latest version from GitHub or from crates.io?

**Comment by sunfu12** [comment]
Yes, it works now. Previous failure is because I didn't install and use related dependencies correctly.Thanks.
