### ISSUE TITLE
Do not pub use model::*

### ISSUE THREAD

**Issue by fabianboesiger** [fabianboesiger/ftx#18]
I think it would be nicer if we used `pub mod model` instead of of `pub use model::*` so that the `rest` and `ws` modules aren't so polluted with model structs.

Library users would then do

```
use ftx::ws::{Ws, model::{Channel, Data, Orderbook}};
```

instead of

```
use ftx::ws::{Channel, Data, Orderbook, Ws};
```

Any opinions?

**Comment by MaxFangX** [comment]
I don't have a particularly strong opinion, but softly disagree for two reasons:

- The only objects that *aren't* in the `ws` and `rest` modules are `Error`, `Result`, and the main `Ws` / `Rest` objects. So taking out the other structs declutters the `rest` and `ws` modules but leaves the `model` module just about as cluttered as `rest`/`ws` were before - it doesn't make that much of a difference imo.
- I haven't seen any crates that namespace with an intermediate `model` module. Having two primary modules `rest` and `ws` is easy to remember from the user's standpoint; namespacing with an intermediate `model` adds a third item that they have to keep in mind.

As long as users don't try to import the entire module (e.g. `use ftx::ws` then `ws::Ws::connect()`), and follow Rust's idiomatic way of importing individual objects (`use ftx::ws::{Ws, Channel, Data}`), the user doesn't bring anything extraneous objects into scope. So I think either configuration is fine, but I slightly favor the current one.

**Comment by fabianboesiger** [comment]
Good points, I think I'll leave it as is.
