### ISSUE TITLE
Unify `OrderSide` and `Side`?

### ISSUE THREAD

**Issue by MaxFangX** [fabianboesiger/ftx#33]
Currently we have `rest::OrderSide` and `rest::Side` which are functionally identical (except that `OrderSide` has a `Serialize` attribute and `Side` doesn't)

Thoughts on unifying them into a single `rest::Side`?
- I don't see any reason why they need to be distinct, and in my own implementing project I've had to manually convert between the two enums several times.
- There aren't too many users of this library yet, so we still have some freedom to make API-breaking changes.

**Comment by fabianboesiger** [comment]
Yes, there is no reason for both of them to exist. I'd suggest only keeping `rest::Side`, and deriving `Serialize`.
