### ISSUE TITLE
Using thiserror or at least implement std::error::Error for the error types?

### ISSUE THREAD

**Issue by dovahcrow** [fabianboesiger/ftx#35]
The error types in this crate are not compatible with std::error::Error, any plan for this?

**Comment by dovahcrow** [comment]
If you are happy with thiserror I can create a PR https://github.com/dovahcrow/ftx/commit/6d76e82c0dcb948cee06066350f41295511b16e8

**Comment by fabianboesiger** [comment]
I agree that at least `std::error::Error` should be implemented for the error enums, but we can also use thiserror if you prefer. PRs are always welcome :-)

**Comment by dovahcrow** [comment]
Thanks! I asked because I know some authors are super anti-{thiserror, failure, error-chain, ...}.
