### ISSUE TITLE
Returning the market field in the ws message?

### ISSUE THREAD

**Issue by dovahcrow** [fabianboesiger/ftx#37]
Currently, if I subscribe two different markets, there's no way for me to distinguish the message: https://github.com/fabianboesiger/ftx/blob/main/src/ws/model.rs#L101. Maybe just expose the Response type and let the user deal with the data structure?

**Comment by MaxFangX** [comment]
I agree we should make the market field available somehow - this is the second time someone has mentioned this need. Currently I subscribe to multiple markets by instantiating a dedicated Ws for each, so when an update comes in I know what market it's for.

I like that the library currently handles pinging, deserialization, and buffering for the user - any clean solution that preserves these would be great.

**Comment by MaxFangX** [comment]
Perhaps a `Symbol` field could be added to the `Data` enum variants for channels that return a market with the `Response`. This would deviate slightly from the FTX API docs but it would preserve the deserialization done on behalf of users (via the 'ResponseData` enums), and would be only a minor API change for projects that have already started working with `Ws`.

**Comment by dovahcrow** [comment]
Yeah, adding the market field would also work.
