### ISSUE TITLE
Trait based request/response?

### ISSUE THREAD

**Issue by dovahcrow** [fabianboesiger/ftx#43]
Just a discussion: do you want to use the trait-based request/response instead of the current method-based one? e.g. I implement the trait-based request/response idea in Deribit rust client https://github.com/dovahcrow/deribit-rs/blob/master/src/models/trading.rs#L32.

The benefit of trait-based request/response is that:
1. No long parameter list of the functions.
2. No need to remember the function names, everything is `request(SomeRequestType) -> SomeRequestType::ResponseType`.
2. API endpoint, signature requirement, request-response type linkage can all be bundled into the trait.
3. No need to specify unneeded parameters by leveraging the Default trait, e.g. 
    ```
    let req = SomeRequest {
                    field_a: val_a,
                     ...Default::default()
    }
    ```
    instead of 
     ```
    client.some_method(
                   val_a, // field_a
                   None, // unneeded_optional_field_b
                   None, // unneeded_optional_field_c
    )
    ```
4. Possible to add sugar functions to the request, e.g. for creating a market order, you just need `let req = Order::market(instrument, qty)`, no need to specify other parameters like `post_only`, `reduce_only` etc.

I can help if you'd like to do the trait-based request/response.

**Comment by fabianboesiger** [comment]
Seems like a very elegant solution, I'm all for it! It will be somewhat tedious to rewrite all the existing request functions, but I think that would be worth it.

**Comment by MaxFangX** [comment]
+1 to @fabianboesiger's comment, everywhere I place an order I have to add a bunch of unnecessary `None` parameters, which clutters the code - but I already use this library extensively across my own projects and as far as I understand, every user would have to rewrite every REST call?

If so, it's mostly a question of how many users are using this library and do we want to force them all to adapt to a fairly large change. Unless the trait-based request/responses is implemented as a new interface for access the existing functions, which would then be backwards-compatible

**Comment by dovahcrow** [comment]
@MaxFangX This can be implemented as backward-compatible: adding a new function `call` that accepts request structs, and every other existing function delegate to the `call` function. Then encourages the user to use the new style `call` function.

**Comment by dovahcrow** [comment]
Hi @fabianboesiger sorry for the delay. I was a little busy these days but will continue the PR this weekend.

**Comment by dovahcrow** [comment]
One thing that requires some design is, FTX also has parameters in the URL where the current trait-based solution does not consider that. i.e. the type who implements `Request` should go directly as solely request body or URL query, but not a part of it goes to the URL and another part goes to the body.

**Comment by fabianboesiger** [comment]
@dovahcrow Nice! I was going to say if you don't have time, I'd pick up on the idea anyway sooner or later, but I'm currently also occupied with other projects for university. However I'll make sure to look into the PR again and look where I can help.

As for the problem with part URL query params and part body params, I don't have a good idea right now either. We should probably come up with a good solution before continue working on the PR. What endpoint has both URL query params and params in the body?

**Comment by fabianboesiger** [comment]
How about we add a method to the `Request` trait:

```
trait Request {
  const METHOD: Method;
  const PATH: &'static str;

  fn params() -> Vec<String> {
    todo!("Returns URL query params of this request")
  }
}
```

To avoid putting the URL query params in the body when serializing, we could simply annotate them with `#[serde(skip_serializing)]`.

**Comment by dovahcrow** [comment]
Good idea. 

A little improvement:
```
fn format_url(&self, fmt_string: &str) -> String {
    fmt_string.into()// default impl
    some_runtime_fmt_lib::format(fmt_string, self.var1, self.var2) // impl with url params
}
```

The downside is we cannot use `format!` anymore.

**Comment by fabianboesiger** [comment]
Why not format the `PATH` and `params()` in the `request` method of the REST API itself that executes all the requests?
If you do something like this:

```
fn url(&self) -> String {
      Self::PATH.into() // default impl
      some_runtime_fmt_lib::format(Self::PATH, self.var1, self.var2) // impl with url params
 }
```

This boilerplate code would have to be written every time some struct implements `Request`.
Option 2 would be better, but I'd prefer to keep the PATH and the query separated. However it wouldn't be a big difference anyway.

**Comment by dovahcrow** [comment]
> This boilerplate code would have to be written every time some struct implements `Request`. 

If we keep the default impl as `Self::PATH.into()` then for URLs without params one does not needs to write this `fn url` boilerplate.

> but I'd prefer to keep the PATH and the query separated.
I was thinking that having a runtime format might degrade the performance comparing to the codegen solution by `format!`.

**Comment by dovahcrow** [comment]
10 method left

**Comment by peepopoggers** [comment]
:+1:
