### ISSUE TITLE
When using  >$ cargo run, error on compile: " could not find `select` in `tokio` "

### ISSUE THREAD

**Issue by peepopoggers** [fabianboesiger/ftx#52]
```sh
> $ cargo run                                                                                                                                                                                           [±master ●]
   Compiling ftx v0.3.1
error[E0433]: failed to resolve: could not find `select` in `tokio`
   --> /home/admin/.cargo/registry/src/github.com-1ecc6299db9ec823/ftx-0.3.1/src/ws/mod.rs:197:20
    |
197 |             tokio::select! {
    |                    ^^^^^^ could not find `select` in `tokio`
```

**Comment by fabianboesiger** [comment]
Which version did you use? The one from crates.io or directly from the repo?

**Comment by peepopoggers** [comment]
@fabianboesiger

**Comment by fabianboesiger** [comment]
Yeah it's not up to date, I should probably upload a new version sometime. Try to directly use the latest version from github using `ftx = { git="https://github.com/fabianboesiger/ftx" }` in your `Cargo.toml`.

**Comment by peepopoggers** [comment]
oh, wow I didnt know you could do that in rust. Maybe because I just started :)
![image](https://user-images.githubusercontent.com/72892531/134294686-e54e5f67-2e76-4362-ba5d-65b66eba1fc5.png)
I get this, because the branch is main not master.

**Comment by peepopoggers** [comment]
![image](https://user-images.githubusercontent.com/72892531/134294887-3207ea28-3399-4075-8ea4-c06877a2fd50.png)
I tried using ftx/tree/main but that won't work either ;<

**Comment by peepopoggers** [comment]
To solve this, I used
`ftx = { git="https://github.com/fabianboesiger/ftx", branch = "main" }`
You could add this to the README so people could add it in easily :)

**Comment by fabianboesiger** [comment]
So everything is working now?

**Comment by peepopoggers** [comment]
![image](https://user-images.githubusercontent.com/72892531/134341566-b12c4108-8d75-4535-85a8-036d5a95629f.png)
![image](https://user-images.githubusercontent.com/72892531/134341599-b2740c43-4f84-42c6-ad21-adb38969c979.png)
Says this while trying to use options

**Comment by fabianboesiger** [comment]
Not entirely sure why you get this error, maybe try `cargo update`.

In general, you may encounter such errors frequently if you use 

```
 ftx = { git="https://github.com/fabianboesiger/ftx", branch = "main" }
```

in your `Cargo.toml` directly. Maybe fork this library and use your fork instead:

```
 ftx = { git="https://github.com/peepopoggers/ftx", branch = "main" }
```

This way, you don't need to handle errors resulting from changes in the ftx library all the time.

**Comment by peepopoggers** [comment]
update worked :+1:
