### ISSUE TITLE
While using place_order: missing field `orderType` at line 1 column 336

### ISSUE THREAD

**Issue by peepopoggers** [fabianboesiger/ftx#66]
This happens when I use the current setup:

```rust
q_main_order = api.place_order(
                        pair,
                        if calculation.islong {ftx::rest::Side::Buy} else {ftx::rest::Side::Sell},
                        None,
                        ftx::rest::OrderType::Market, //change this later so you dont get terrible fees
                        calculation.quantity/q_market.price,
                        None,
                        None,
                        None, //when implimenting close limit order change to true
                        None
                    ).await?;
```

Also it does actually execute the order on FTX but it errors I think when trying to get a result. I have no idea why it thinks ordertype is missing.

Gives this error:
```
While using place_order: missing field orderType at line 1 column 336
```

**Comment by fabianboesiger** [comment]
It seems like this should be a compile time error.

If your code compiles and executes the order, where does the error come from?

What IDE are you using? What is the output of `cargo check`?

**Comment by peepopoggers** [comment]
Will test again

**Comment by fabianboesiger** [comment]
It seems like PR #63 broke ordering. I'll try to fix it in the next hours.

**Comment by peepopoggers** [comment]
oopsie :man_facepalming:
I was not sure about how the project was structured, sorry about that.
If you make a fix I will pull it and I will test it with an order and a limit order.

**Comment by fabianboesiger** [comment]
No worries, I should've looked a bit closer if it was your first contribution to a Rust project. I'll fix it in a minute.

**Comment by peepopoggers** [comment]
Yeah, I only started learning rust a couple weeks ago. Guess you could proceed my commits with caution :smile_cat:
