### ISSUE TITLE
"Not logged in" error introduced in request / response

### ISSUE THREAD

**Issue by MaxFangX** [fabianboesiger/ftx#78]
I am currently in the process of tracking down a "Not logged in" error appearing in my log messages after updating my fork of this library.

The tests do not reproduce the error, but my implementing codebase (~7k lines) does. Here are some example log messages:

```
[00:10:16.484965 DEBUG] response '200 OK' for https://ftx.com/api/positions
[00:10:16.955672 DEBUG] response '401 Unauthorized' for https://ftx.com/api/orders?market=ETH-PERP
[00:10:16.956057 ERROR] Error during reset: Could not cancel excess limit orders: Could not fetch open orders: Api error: Not logged in
```

It appears that some endpoints (e.g. `/positions`) work fine, but there is an error with the `/orders` endpoint.

I've bisected my own codebase and tracked down the offending commit to the one where I updated my ftx lib. I'm currently in the process of tracking down which commit it's in and so far have narrowed it down to one of the ones in the request / response PR #47. Opening this issue here because I was hoping you might have some ideas @dovahcrow as to what is going on.

**Comment by MaxFangX** [comment]
Here's my current progress on bisecting within this library:

BAD 0e45961 Merge pull request #77 from peepopoggers/patch-1
BAD d82a0d5 Merge pull request #47 from dovahcrow/reqresp (Oct 12)

...

NONCOMPILING 0792c2e implement subaccounts and place_order

GOOD 1dec168 Merge pull request #68 from georgewhewell/withdraw (Oct 8)
GOOD 75fc7ec Update README.md (Sep 30)
GOOD cb3a7d7 Merge pull request #55 from jaredwolff/timestamp-for-rest-commands (Sep 26)
GOOD a2e7b8a Merge pull request #53 from fabianboesiger/connection-options (Sep 22)
GOOD 39be455 Make CoinInfo fields public (Sep 21)

**Comment by dovahcrow** [comment]
@MaxFangX Can you try out the fix to see if it works? a.k.a. cargo patch the ftx crate
