### ISSUE TITLE
sending fast requests 

### ISSUE THREAD

**Issue by qwertynat** [fabianboesiger/ftx#89]
Hi, I may be showing my Rust naivety here, but am I correct in thinking the the REST implementation is not able to a call to another request until the current one finishes?

For example using roughly Rust ish pseudo code i would like to do the following without blocking.

`
loop {

    let order = api.request(PlaceOrder::new(/*fill this in to place a market but of 1 btc */));

    //check if order has completed yet if not continue to loop and send orders 

    // if order has compelted let's process then continue to market buy 1 btc in this loop

}

`

I apoligise if this is not the correct forum to ask this question, and you can happily delete if this is the case. 

thanks!

**Comment by fabianboesiger** [comment]
`api.request` returns a [Future](https://doc.rust-lang.org/std/future/trait.Future.html), so you can do requests concurrently, or block until the previous one was finished. You'll need an async runtime such as [tokio](https://docs.rs/tokio/1.14.0/tokio/time/struct.Sleep.html) to properly execute Futures.

If you want multiple non-blocking requests, you can collect their futures in a vec, and then use [join_all](https://docs.rs/futures/0.3.18/futures/future/fn.join_all.html) to execute them concurrently. Something like:

```
let mut futures = Vec::new();
loop {
    futures.push(api.request(...));
}
try_join_all(futures).await?;
```

**Comment by dovahcrow** [comment]
@fabianboesiger Or maybe he's asking something like this: https://github.com/dovahcrow/deribit-rs/blob/master/examples/subscription.rs#L37

in deribit-rs the request sending is decoupled with receiving (the first await is for sending, the second one is for receiving)
```
let _ = client.call(req).await?.await?;
```
In ftx-rs this might be hard because it uses HTTP rather than Websocket

**Comment by fabianboesiger** [comment]
@dovahcrow oh that's a nice idea for WebSocket APIs. If surely would be possible somehow with HTTP requests, but I don't think that this would be an advantage worth the implementation effort and additional complexity.

**Comment by qwertynat** [comment]
Again excuse my Rust inexperience, but @fabianboesiger in your example what happens if i want to send another request after i have called try_join_all ? doesn't try_join_all return after all futures are complete?

**Comment by fabianboesiger** [comment]
@qwertynat Yes, after you call `try_join_all`, all the futures in the Vec are completed. However, you can still create new requests simply by calling `api.request(...)` again, which returns a new, unresolved future. If you are unfamiliar with async programming, I recommend reading [Getting Started - Asynchronous Programming](https://rust-lang.github.io/async-book/01_getting_started/01_chapter.html).
